name: Lint and Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run ESLint and Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run Prettier check
        run: npm run format:check # package.jsonに "format:check": "prettier --check ." を追加
      - name: Run ESLint
        run: npm run lint # package.jsonに "lint": "eslint --ext .js,.jsx,.ts,.tsx ." を追加
